services:
  web:
    build: .
    command: sh -c 'alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 80'
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "5678:5678"  # Для debugpy (если нужно)
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
    env_file: 
      - .env
    networks:
      - fastapi-taskman-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - fastapi-taskman-network

networks:
  fastapi-taskman-network:
    driver: bridge

volumes:
  postgres_data: