"""добавил тип данных NOne в дату

Revision ID: a2880f9337bc
Revises: f2efaf730af6
Create Date: 2025-05-05 14:08:16.896740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2880f9337bc'
down_revision: Union[str, None] = 'f2efaf730af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
