"""Добавлена сложность

Revision ID: e559fd943037
Revises: bf69f4f554a2
Create Date: 2025-05-05 19:33:50.034321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e559fd943037'
down_revision: Union[str, None] = 'bf69f4f554a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complexity', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complexity')
    # ### end Alembic commands ###
